# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PasswordEditPrompt.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(495, 140)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(9, 10, 471, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.password_widget = QtWidgets.QWidget(Form)
        self.password_widget.setGeometry(QtCore.QRect(10, 40, 475, 50))
        self.password_widget.setObjectName("password_widget")
        self.field_password = QtWidgets.QLineEdit(self.password_widget)
        self.field_password.setGeometry(QtCore.QRect(0, 0, 475, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.field_password.sizePolicy().hasHeightForWidth())
        self.field_password.setSizePolicy(sizePolicy)
        self.field_password.setMaxLength(32)
        self.field_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.field_password.setObjectName("field_password")
        self.text_strength = QtWidgets.QLabel(self.password_widget)
        self.text_strength.setGeometry(QtCore.QRect(0, 28, 474, 21))
        self.text_strength.setStyleSheet("color: rgb(170, 0, 0);")
        self.text_strength.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.text_strength.setWordWrap(True)
        self.text_strength.setObjectName("text_strength")
        self.text_eye = QtWidgets.QLabel(self.password_widget)
        self.text_eye.setGeometry(QtCore.QRect(449, 2, 21, 20))
        self.text_eye.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.text_eye.setObjectName("text_eye")
        self.toggle_visible = QtWidgets.QPushButton(self.password_widget)
        self.toggle_visible.setGeometry(QtCore.QRect(447, 0, 25, 25))
        self.toggle_visible.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toggle_visible.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.toggle_visible.setText("")
        self.toggle_visible.setFlat(True)
        self.toggle_visible.setObjectName("toggle_visible")
        self.buttons = QtWidgets.QWidget(Form)
        self.buttons.setGeometry(QtCore.QRect(10, 100, 475, 29))
        self.buttons.setObjectName("buttons")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.buttons)
        self.horizontalLayout_2.setContentsMargins(275, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ok = QtWidgets.QPushButton(self.buttons)
        self.ok.setEnabled(False)
        self.ok.setObjectName("ok")
        self.horizontalLayout_2.addWidget(self.ok)
        self.cancel = QtWidgets.QPushButton(self.buttons)
        self.cancel.setObjectName("cancel")
        self.horizontalLayout_2.addWidget(self.cancel)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Изменить пароль"))
        self.label.setText(_translate("Form", "Введите новый пароль:"))
        self.field_password.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Пароль должен быть длины 8 или более символов, а также содержать строчные и заглавные буквы, цифры и хотя бы один из следующих символов: @ $ ! % * ? &amp;</span></p></body></html>"))
        self.text_strength.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#aaaaaa;\">■■■■■■</span></p></body></html>"))
        self.text_eye.setText(_translate("Form", "👁"))
        self.ok.setText(_translate("Form", "ОК"))
        self.cancel.setText(_translate("Form", "Отмена"))
